services:
  wishmiton:
    container_name: wishmiton
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - 80:8000
    volumes:
      - .:/app/wishmiton
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, wishmitin:8000
      APP_ENV: dev
      MYSQL_HOST: "${MYSQL_HOST}"
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - mariadb
    networks:
      - "app_network"

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb:10.11
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    env_file:
      - .env
    networks:
      - "app_network"

  phpmyadmin:
    container_name: "phpmyadmin_service"
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: "${MYSQL_HOST}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "8080:80"
    depends_on:
      - mariadb 
    restart: always
    env_file:
      - .env
    networks:
      - "app_network"

volumes:
  mariadb_data:

networks:
  app_network: